# Generated by Django 4.0.6 on 2022-07-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(max_length=275),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(max_length=300),
        ),
    ]
