# Generated by Django 4.0.6 on 2022-07-20 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_api', '0002_alter_book_author_alter_note_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tracker', to=settings.AUTH_USER_MODEL),
        ),
    ]
