# Generated by Django 4.0.6 on 2022-07-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_alter_note_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='library_api.book'),
        ),
    ]
